services:
  django:
    container_name: workout_planner_django
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/WorkoutPlanner
    env_file:
      - .env
